# Generated by Django 3.1.3 on 2020-11-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], default='Medium', max_length=50)),
                ('shape', models.CharField(choices=[('Regular', 'Regular'), ('Square', 'Square')], default='Regular', max_length=50)),
                ('toppings', models.ManyToManyField(to='api.Toppings')),
            ],
        ),
    ]
