# Generated by Django 3.1.3 on 2020-11-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='customer_name',
            field=models.CharField(default='shubham', max_length=100),
            preserve_default=False,
        ),
    ]
