# Generated by Django 3.1.3 on 2020-11-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pizza_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='shape',
            field=models.CharField(choices=[('regular', 'regular'), ('square', 'square')], default='regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('large', 'large'), ('medium', 'medium'), ('small', 'small')], default='medium', max_length=50),
        ),
    ]
